id: DF7877E8C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-03-23T11:05:26+00:00'
last_modified: '2022-05-30T07:52:05.234524+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    d558:
      image_group_id: I1PD95942
      title: ཚད་མ་རིགས་པར་འཇུག་པའི་སྒོ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1198
      order: 97
      base_file: d558.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
