id: P0E66D041
initial_creation_type: ocr
source_metadata:
  volumes:
    008d117380594e57a6954990f2660e06:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: ཚད་མ་རིགས་པར་འཇུག་པའི་སྒོ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1198
      volume_number: 97
